### ISSUE TITLE
Option to select a specific player

### ISSUE THREAD

**Issue by bonnebulle** [spookylukey/playerdo#2]
Thanks, works like ``playerctl`` but detects more players (and some ones shared on Lan)
Cool. Works to mush well ;)
An option (parameter) but we cant select one
Something like :
``player_do quodlibet play``
should help
Yes, it's a Feature request
Thanks

**Comment by spookylukey** [comment]
This is a good suggestion, thanks. I've added this as `--player` or `-p` option, plus overhauled quite a few things, and released 2.1.
